### ISSUE TITLE
Feature Request: Let us buy you a coffee

### ISSUE THREAD

**Issue by sqldiablo** [Silvenga/unifi-udm-api-proxy#11]
Thanks for making this proxy, it helped me get my cameras working in Home Assistant Core again following my upgrade to the Unify Dream Machine Pro! Please add a "buy me a coffee" or "buy me a beer" link in your README so I can throw some cash...err...appreciation your way. :-)

**Comment by Silvenga** [comment]
Hey @sqldiablo - messages like this mean a lot to me. Thanks! I'm happy someone is finding my projects useful.

I added a buymeacoffee.com link on this repo. Hopefully, I set it up correctly. 😹
