### ISSUE TITLE
500 Internal Server Error when accessing /api/cameras route

### ISSUE THREAD

**Issue by nideville** [Silvenga/unifi-udm-api-proxy#14]
Hi,

I'm trying to use your proxy with this tool https://github.com/unifi-toolbox/unifi-protect-video-downloader
I also replicate the same issue using postman directly on your proxy

Auth works fine I get a token + json result of my auth
When I try to access` /api/cameras` route, I get a `500 Internet Server Error`

I have this issue on a Unifi Cloud Key Plus 2+ running Unifi OS 2.1.7 & Protect 1.17.4 with only one camera

Is there a way to get logs from your container ? Any idea on how to debug this ?

Thanks 
Nicolas

**Comment by briis** [comment]
The proxy is no longer needed for the UniFi Protect integration to work.

**Comment by nideville** [comment]
ok, do you know where I can find some details about this (api routes to call for auth & camera access) ? the owner of unifi-protect-video-downloader still refers to your proxy for cloud key. (and his code does not seems to work if I put my cloud IP directly)

**Comment by danielfernau** [comment]
Hi there –

In case UI re-added the "old" API paths to UniFiOS on ports 443 or 7443, I'll remove the reference to the proxy from my project's docs. Haven't had a chance to look at their recent changes yet... Therefore, thanks for the heads-up!

**Comment by danielfernau** [comment]
Hi again!

The proxy is indeed no longer required for apps to properly communicate with a UniFi OS Protect instance. I've updated my tool to reflect UI's recent updates to their platform and API. With that, I think this issue is now resolved and can be closed. Thanks everyone!

**Comment by Silvenga** [comment]
Apologies, been busy lately. So all good? Do we know what the change was?

**Comment by danielfernau** [comment]
No worries, me too. Thanks for the reply, though!
Finally had a chance to have a look at it this weekend. 

UI has mapped/moved the entire Protect API to 
`https://{ip-address}:443/proxy/protect/api/...` 
and authentication is now at 
`https://{ip-address}:443/api/auth/login`. 

Updated the code on my end, works fine now. Can be closed here IMO.

**Comment by Silvenga** [comment]
Thanks for that @danielfernau! I'll add it to my todo list to check out (just so much to do 😿).

**Comment by danielfernau** [comment]
Sounds good @Silvenga – feel free to reach out any time if you need more details on the API changes. 

Yeah, I know that feeling. So much stuff going on everywhere over the past couple of months... One thing at a time! 👍
