### ISSUE TITLE
Example of how to confirm container is working

### ISSUE THREAD

**Issue by johntdyer** [Silvenga/unifi-udm-api-proxy#2]
Do you have an example CURL I can use against this to confirm it is infa

**Comment by Silvenga** [comment]
The latest image pushed supports health checks, but if you want to validate that the proxy is proxying, the following should return a not authorized from the UDM.

```
curl https://localhost/api/auth --insecure -H "Content-Type: application/json; charset=utf-8" -H "Content-Length: 0" -X POST --http1.1
```

```
{
  "errors": [
    "Invalid username or password"
  ]
}
```

**Comment by Silvenga** [comment]
Closing for now, feel free to re-open.
